### ISSUE TITLE
Permite incluir o mesmo produto várias vezes no carrinho

### ISSUE THREAD

**Issue by danilloguimaraes** [acsantosabino/angular-med-store#32]
O mesmo produto pode ser incluído várias vezes no carrinho e o sistema se comporta como se fossem produtos diferentes. Acho que teríamos que identificar que o o produto já estava no carrinho e não fazer nada, ou substituir pela nova quantidade informada.

**Comment by acsantosabino** [comment]
Pensei nisso também, só não sei se vale a pena trabalha nisso.
Mas se quiser, pode fazer.

**Comment by acsantosabino** [comment]
Vou corrigi isso
